### ISSUE TITLE
关于论文中图2 tsne可视化的问题 ’

### ISSUE THREAD

**Issue by ChibisukeDragon** [csuhan/opendet2#7]
@csuhan 
您好，我想请教论文中的一个点。
Figure 2. t-SNE visualization of latent features.
这里提到彩色的点是VOC类别（已知），而黑色三角点则是非VOC类别（未知，取自COCO）

在您的工作中，您将未知类别设定为数量为1的1个类别（而不是更多数量），这样训出来的模型，我们就很自然地认为，未知类别也会聚成一个簇，就像图2 (b)中一样。同时还有一些离散点，分散在各个已知类别簇中。

但是实际上来看，1个未知类别，它应该蕴含了众多潜在的类别，例如COCO类别数量-VOC类别数量=80-20=60，也就是1个未知类别可能就蕴含了潜在的60个类别。而将60个类别的特征聚集在了一起，形成了图2 (b)，这是不是有点奇怪？也就是想问，只有1个未知类的类中心，是不是不太合理？

想请教您的看法，谢谢！

**Comment by csuhan** [comment]
感谢提问，这是个好问题！

理想情况下，我们当然希望不同的unknown类也能区分开来。
然而由于我们只在known类上训练，unknown所对应的 (proposal) features必然位于低响应区域，即混成一个cluster，无法相互区分。
将这些低响应的cluster划分为多个区域是合理的，我们也尝试过类似的策略。但由于缺乏监督信息，这种划分并不能将不同的unknown类区分开来。
同时由于我们的任务仅仅需要区分known/unknown，因此不需要区分unknown类（相反，zero-shot object detection需要区分unseen类的类别）。

**Comment by ChibisukeDragon** [comment]
@csuhan 感谢您的解答~！我又想了想，有一个新的疑问。
对于您说的“unknown所对应的 (proposal) features必然位于低响应区域，即混成一个cluster”，也就是说：unknown类本来就会形成一个簇，即使我们还未采用开放任务方法来改进原始模型？
那么，对于一个非常原始的目标检测方法，不加任何改进，只在VOC上训完后，我在VOC和COCO上绘制特征可视化，是不是就对应于您论文中的图2 (a)的内容？未经任何改动，那些unknown类本身就会形成一个小簇？这感觉就比较诡异了，是我理解有误吗？我觉得，unknown类在特征空间中，初始时应该会随机分布于已知类簇的周围，或许会形成小簇，或许就分散得很开。。

**Comment by csuhan** [comment]
This is validated by some works in open-set recognition.
For example, Fig.6 in [http://arxiv.org/abs/2110.06207](http://arxiv.org/abs/2110.06207), Fig.1 in [http://arxiv.org/abs/2103.00953](http://arxiv.org/abs/2103.00953), Fig.5 in [https://arxiv.org/abs/2103.15086](https://arxiv.org/abs/2103.15086).

**Comment by ChibisukeDragon** [comment]
That's amazing. Thanks a lot!

**Comment by jinweiisgreat** [comment]
说一下我的理解和问题：
1. 做不了细分类的原因是，训练阶段的mini-batch是只获取IoU0.5以上的框，目的就是对已知instance建模。因此整个模型就没有考虑到unknown instance。只是在test的时候，或者说，相当于后处理方法，给目标一个分数来判断是否是已知或者未知，这也是为什么文中会说：“Furthermore, since background proposals usually overwhelm the mini-batch, we sample the same number of foreground and background proposals, enabling our model to recall unknown objects from the background class.”
2. 我的问题是，我在 $L_{IC}$只找到正样本部分，没找到处理负样本的代码。这虽然会让正样本类会更近，但并不会让不同类的样本更远呀？
希望得到回复！谢谢
